# Generated by Django 5.2.4 on 2025-08-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsmeet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
